//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.14 at 08:28:06 AM EDT 
//


package com.nextivr.voicexml21;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for height.scale.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="height.scale"&amp;gt;
 *   &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *     &amp;lt;enumeration value="x-high"/&amp;gt;
 *     &amp;lt;enumeration value="high"/&amp;gt;
 *     &amp;lt;enumeration value="medium"/&amp;gt;
 *     &amp;lt;enumeration value="low"/&amp;gt;
 *     &amp;lt;enumeration value="x-low"/&amp;gt;
 *     &amp;lt;enumeration value="default"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "height.scale")
@XmlEnum
public enum HeightScale {

    @XmlEnumValue("x-high")
    X_HIGH("x-high"),
    @XmlEnumValue("high")
    HIGH("high"),
    @XmlEnumValue("medium")
    MEDIUM("medium"),
    @XmlEnumValue("low")
    LOW("low"),
    @XmlEnumValue("x-low")
    X_LOW("x-low"),
    @XmlEnumValue("default")
    DEFAULT("default");
    private final String value;

    HeightScale(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HeightScale fromValue(String v) {
        for (HeightScale c: HeightScale.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
