//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.14 at 08:28:06 AM EDT 
//


package com.nextivr.voicexml21;

import javax.xml.namespace.QName;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nextivr.voicexml21 package. 
 * &lt;p&gt;An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Grammar_QNAME = new QName("http://www.w3.org/2001/vxml", "grammar");
    private final static QName _Aws_QNAME = new QName("http://www.w3.org/2001/vxml", "aws");
    private final static QName _Struct_QNAME = new QName("http://www.w3.org/2001/vxml", "struct");
    private final static QName _Speak_QNAME = new QName("http://www.w3.org/2001/vxml", "speak");
    private final static QName _P_QNAME = new QName("http://www.w3.org/2001/vxml", "p");
    private final static QName _S_QNAME = new QName("http://www.w3.org/2001/vxml", "s");
    private final static QName _Voice_QNAME = new QName("http://www.w3.org/2001/vxml", "voice");
    private final static QName _Prosody_QNAME = new QName("http://www.w3.org/2001/vxml", "prosody");
    private final static QName _Audio_QNAME = new QName("http://www.w3.org/2001/vxml", "audio");
    private final static QName _Desc_QNAME = new QName("http://www.w3.org/2001/vxml", "desc");
    private final static QName _Emphasis_QNAME = new QName("http://www.w3.org/2001/vxml", "emphasis");
    private final static QName _Sub_QNAME = new QName("http://www.w3.org/2001/vxml", "sub");
    private final static QName _SayAs_QNAME = new QName("http://www.w3.org/2001/vxml", "say-as");
    private final static QName _Phoneme_QNAME = new QName("http://www.w3.org/2001/vxml", "phoneme");
    private final static QName _Break_QNAME = new QName("http://www.w3.org/2001/vxml", "break");
    private final static QName _Mark_QNAME = new QName("http://www.w3.org/2001/vxml", "mark");
    private final static QName _Value_QNAME = new QName("http://www.w3.org/2001/vxml", "value");
    private final static QName _Enumerate_QNAME = new QName("http://www.w3.org/2001/vxml", "enumerate");
    private final static QName _Prompt_QNAME = new QName("http://www.w3.org/2001/vxml", "prompt");
    private final static QName _Error_QNAME = new QName("http://www.w3.org/2001/vxml", "error");
    private final static QName _Help_QNAME = new QName("http://www.w3.org/2001/vxml", "help");
    private final static QName _Noinput_QNAME = new QName("http://www.w3.org/2001/vxml", "noinput");
    private final static QName _Nomatch_QNAME = new QName("http://www.w3.org/2001/vxml", "nomatch");
    private final static QName _IfForeach_QNAME = new QName("http://www.w3.org/2001/vxml", "foreach");
    private final static QName _RuleToken_QNAME = new QName("http://www.w3.org/2001/vxml", "token");
    private final static QName _RuleRuleref_QNAME = new QName("http://www.w3.org/2001/vxml", "ruleref");
    private final static QName _RuleItem_QNAME = new QName("http://www.w3.org/2001/vxml", "item");
    private final static QName _RuleOneOf_QNAME = new QName("http://www.w3.org/2001/vxml", "one-of");
    private final static QName _RuleTag_QNAME = new QName("http://www.w3.org/2001/vxml", "tag");
    private final static QName _RuleExample_QNAME = new QName("http://www.w3.org/2001/vxml", "example");
    private final static QName _OriginalMixedGrammarLexicon_QNAME = new QName("http://www.w3.org/2001/vxml", "lexicon");
    private final static QName _OriginalMixedGrammarMeta_QNAME = new QName("http://www.w3.org/2001/vxml", "meta");
    private final static QName _OriginalMixedGrammarMetadata_QNAME = new QName("http://www.w3.org/2001/vxml", "metadata");
    private final static QName _OriginalMixedGrammarRule_QNAME = new QName("http://www.w3.org/2001/vxml", "rule");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nextivr.voicexml21
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Grammar }
     * 
     */
    public Grammar createGrammar() {
        return new Grammar();
    }

    /**
     * Create an instance of {@link Speak }
     * 
     */
    public Speak createSpeak() {
        return new Speak();
    }

    /**
     * Create an instance of {@link Paragraph }
     * 
     */
    public Paragraph createParagraph() {
        return new Paragraph();
    }

    /**
     * Create an instance of {@link Sentence }
     * 
     */
    public Sentence createSentence() {
        return new Sentence();
    }

    /**
     * Create an instance of {@link Voice }
     * 
     */
    public Voice createVoice() {
        return new Voice();
    }

    /**
     * Create an instance of {@link Prosody }
     * 
     */
    public Prosody createProsody() {
        return new Prosody();
    }

    /**
     * Create an instance of {@link Audio }
     * 
     */
    public Audio createAudio() {
        return new Audio();
    }

    /**
     * Create an instance of {@link Desc }
     * 
     */
    public Desc createDesc() {
        return new Desc();
    }

    /**
     * Create an instance of {@link Emphasis }
     * 
     */
    public Emphasis createEmphasis() {
        return new Emphasis();
    }

    /**
     * Create an instance of {@link Sub }
     * 
     */
    public Sub createSub() {
        return new Sub();
    }

    /**
     * Create an instance of {@link SayAs }
     * 
     */
    public SayAs createSayAs() {
        return new SayAs();
    }

    /**
     * Create an instance of {@link Phoneme }
     * 
     */
    public Phoneme createPhoneme() {
        return new Phoneme();
    }

    /**
     * Create an instance of {@link Break }
     * 
     */
    public Break createBreak() {
        return new Break();
    }

    /**
     * Create an instance of {@link Mark }
     * 
     */
    public Mark createMark() {
        return new Mark();
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link Enumerate }
     * 
     */
    public Enumerate createEnumerate() {
        return new Enumerate();
    }

    /**
     * Create an instance of {@link Assign }
     * 
     */
    public Assign createAssign() {
        return new Assign();
    }

    /**
     * Create an instance of {@link Block }
     * 
     */
    public Block createBlock() {
        return new Block();
    }

    /**
     * Create an instance of {@link Clear }
     * 
     */
    public Clear createClear() {
        return new Clear();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link Disconnect }
     * 
     */
    public Disconnect createDisconnect() {
        return new Disconnect();
    }

    /**
     * Create an instance of {@link Exit }
     * 
     */
    public Exit createExit() {
        return new Exit();
    }

    /**
     * Create an instance of {@link ForeachNotInPromptType }
     * 
     */
    public ForeachNotInPromptType createForeachNotInPromptType() {
        return new ForeachNotInPromptType();
    }

    /**
     * Create an instance of {@link Goto }
     * 
     */
    public Goto createGoto() {
        return new Goto();
    }

    /**
     * Create an instance of {@link If }
     * 
     */
    public If createIf() {
        return new If();
    }

    /**
     * Create an instance of {@link Log }
     * 
     */
    public Log createLog() {
        return new Log();
    }

    /**
     * Create an instance of {@link Reprompt }
     * 
     */
    public Reprompt createReprompt() {
        return new Reprompt();
    }

    /**
     * Create an instance of {@link Return }
     * 
     */
    public Return createReturn() {
        return new Return();
    }

    /**
     * Create an instance of {@link Script }
     * 
     */
    public Script createScript() {
        return new Script();
    }

    /**
     * Create an instance of {@link Submit }
     * 
     */
    public Submit createSubmit() {
        return new Submit();
    }

    /**
     * Create an instance of {@link Throw }
     * 
     */
    public Throw createThrow() {
        return new Throw();
    }

    /**
     * Create an instance of {@link Var }
     * 
     */
    public Var createVar() {
        return new Var();
    }

    /**
     * Create an instance of {@link VxmlSpeak }
     * 
     */
    public VxmlSpeak createVxmlSpeak() {
        return new VxmlSpeak();
    }

    /**
     * Create an instance of {@link Elseif }
     * 
     */
    public Elseif createElseif() {
        return new Elseif();
    }

    /**
     * Create an instance of {@link Else }
     * 
     */
    public Else createElse() {
        return new Else();
    }

    /**
     * Create an instance of {@link Catch }
     * 
     */
    public Catch createCatch() {
        return new Catch();
    }

    /**
     * Create an instance of {@link BasicEventHandler }
     * 
     */
    public BasicEventHandler createBasicEventHandler() {
        return new BasicEventHandler();
    }

    /**
     * Create an instance of {@link Choice }
     * 
     */
    public Choice createChoice() {
        return new Choice();
    }

    /**
     * Create an instance of {@link MixedGrammar }
     * 
     */
    public MixedGrammar createMixedGrammar() {
        return new MixedGrammar();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link Filled }
     * 
     */
    public Filled createFilled() {
        return new Filled();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link Option }
     * 
     */
    public Option createOption() {
        return new Option();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Form }
     * 
     */
    public Form createForm() {
        return new Form();
    }

    /**
     * Create an instance of {@link Initial }
     * 
     */
    public Initial createInitial() {
        return new Initial();
    }

    /**
     * Create an instance of {@link com.nextivr.voicexml21.Object }
     * 
     */
    public com.nextivr.voicexml21.Object createObject() {
        return new com.nextivr.voicexml21.Object();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link Record }
     * 
     */
    public Record createRecord() {
        return new Record();
    }

    /**
     * Create an instance of {@link Subdialog }
     * 
     */
    public Subdialog createSubdialog() {
        return new Subdialog();
    }

    /**
     * Create an instance of {@link Transfer }
     * 
     */
    public Transfer createTransfer() {
        return new Transfer();
    }

    /**
     * Create an instance of {@link Menu }
     * 
     */
    public Menu createMenu() {
        return new Menu();
    }

    /**
     * Create an instance of {@link MetaVxml }
     * 
     */
    public MetaVxml createMetaVxml() {
        return new MetaVxml();
    }

    /**
     * Create an instance of {@link MetadataVxml }
     * 
     */
    public MetadataVxml createMetadataVxml() {
        return new MetadataVxml();
    }

    /**
     * Create an instance of {@link Vxml }
     * 
     */
    public Vxml createVxml() {
        return new Vxml();
    }

    /**
     * Create an instance of {@link Ruleref }
     * 
     */
    public Ruleref createRuleref() {
        return new Ruleref();
    }

    /**
     * Create an instance of {@link Token }
     * 
     */
    public Token createToken() {
        return new Token();
    }

    /**
     * Create an instance of {@link OneOf }
     * 
     */
    public OneOf createOneOf() {
        return new OneOf();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link Rule }
     * 
     */
    public Rule createRule() {
        return new Rule();
    }

    /**
     * Create an instance of {@link Lexicon }
     * 
     */
    public Lexicon createLexicon() {
        return new Lexicon();
    }

    /**
     * Create an instance of {@link Meta }
     * 
     */
    public Meta createMeta() {
        return new Meta();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link SsmlMetadata }
     * 
     */
    public SsmlMetadata createSsmlMetadata() {
        return new SsmlMetadata();
    }

    /**
     * Create an instance of {@link SsmlMeta }
     * 
     */
    public SsmlMeta createSsmlMeta() {
        return new SsmlMeta();
    }

    /**
     * Create an instance of {@link SsmlLexicon }
     * 
     */
    public SsmlLexicon createSsmlLexicon() {
        return new SsmlLexicon();
    }

    /**
     * Create an instance of {@link ForeachInPromptType }
     * 
     */
    public ForeachInPromptType createForeachInPromptType() {
        return new ForeachInPromptType();
    }

    /**
     * Create an instance of {@link OriginalMixedGrammar }
     * 
     */
    public OriginalMixedGrammar createOriginalMixedGrammar() {
        return new OriginalMixedGrammar();
    }

    /**
     * Create an instance of {@link OriginalMark }
     * 
     */
    public OriginalMark createOriginalMark() {
        return new OriginalMark();
    }

    /**
     * Create an instance of {@link OriginalSayAs }
     * 
     */
    public OriginalSayAs createOriginalSayAs() {
        return new OriginalSayAs();
    }

    /**
     * Create an instance of {@link OriginalAudio }
     * 
     */
    public OriginalAudio createOriginalAudio() {
        return new OriginalAudio();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Grammar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Grammar }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "grammar")
    public JAXBElement<Grammar> createGrammar(Grammar value) {
        return new JAXBElement<Grammar>(_Grammar_QNAME, Grammar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link java.lang.Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "aws")
    public JAXBElement<java.lang.Object> createAws(java.lang.Object value) {
        return new JAXBElement<java.lang.Object>(_Aws_QNAME, java.lang.Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link java.lang.Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link java.lang.Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "struct")
    public JAXBElement<java.lang.Object> createStruct(java.lang.Object value) {
        return new JAXBElement<java.lang.Object>(_Struct_QNAME, java.lang.Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Speak }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Speak }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "speak")
    public JAXBElement<Speak> createSpeak(Speak value) {
        return new JAXBElement<Speak>(_Speak_QNAME, Speak.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Paragraph }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Paragraph }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "p", substitutionHeadNamespace = "http://www.w3.org/2001/vxml", substitutionHeadName = "struct")
    public JAXBElement<Paragraph> createP(Paragraph value) {
        return new JAXBElement<Paragraph>(_P_QNAME, Paragraph.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sentence }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Sentence }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "s", substitutionHeadNamespace = "http://www.w3.org/2001/vxml", substitutionHeadName = "struct")
    public JAXBElement<Sentence> createS(Sentence value) {
        return new JAXBElement<Sentence>(_S_QNAME, Sentence.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Voice }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Voice }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "voice", substitutionHeadNamespace = "http://www.w3.org/2001/vxml", substitutionHeadName = "aws")
    public JAXBElement<Voice> createVoice(Voice value) {
        return new JAXBElement<Voice>(_Voice_QNAME, Voice.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prosody }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Prosody }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "prosody", substitutionHeadNamespace = "http://www.w3.org/2001/vxml", substitutionHeadName = "aws")
    public JAXBElement<Prosody> createProsody(Prosody value) {
        return new JAXBElement<Prosody>(_Prosody_QNAME, Prosody.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Audio }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Audio }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "audio", substitutionHeadNamespace = "http://www.w3.org/2001/vxml", substitutionHeadName = "aws")
    public JAXBElement<Audio> createAudio(Audio value) {
        return new JAXBElement<Audio>(_Audio_QNAME, Audio.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Desc }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Desc }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "desc")
    public JAXBElement<Desc> createDesc(Desc value) {
        return new JAXBElement<Desc>(_Desc_QNAME, Desc.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Emphasis }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Emphasis }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "emphasis", substitutionHeadNamespace = "http://www.w3.org/2001/vxml", substitutionHeadName = "aws")
    public JAXBElement<Emphasis> createEmphasis(Emphasis value) {
        return new JAXBElement<Emphasis>(_Emphasis_QNAME, Emphasis.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sub }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Sub }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "sub", substitutionHeadNamespace = "http://www.w3.org/2001/vxml", substitutionHeadName = "aws")
    public JAXBElement<Sub> createSub(Sub value) {
        return new JAXBElement<Sub>(_Sub_QNAME, Sub.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SayAs }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SayAs }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "say-as", substitutionHeadNamespace = "http://www.w3.org/2001/vxml", substitutionHeadName = "aws")
    public JAXBElement<SayAs> createSayAs(SayAs value) {
        return new JAXBElement<SayAs>(_SayAs_QNAME, SayAs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Phoneme }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Phoneme }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "phoneme", substitutionHeadNamespace = "http://www.w3.org/2001/vxml", substitutionHeadName = "aws")
    public JAXBElement<Phoneme> createPhoneme(Phoneme value) {
        return new JAXBElement<Phoneme>(_Phoneme_QNAME, Phoneme.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Break }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Break }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "break", substitutionHeadNamespace = "http://www.w3.org/2001/vxml", substitutionHeadName = "aws")
    public JAXBElement<Break> createBreak(Break value) {
        return new JAXBElement<Break>(_Break_QNAME, Break.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Mark }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Mark }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "mark", substitutionHeadNamespace = "http://www.w3.org/2001/vxml", substitutionHeadName = "aws")
    public JAXBElement<Mark> createMark(Mark value) {
        return new JAXBElement<Mark>(_Mark_QNAME, Mark.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Value }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Value }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "value", substitutionHeadNamespace = "http://www.w3.org/2001/vxml", substitutionHeadName = "aws")
    public JAXBElement<Value> createValue(Value value) {
        return new JAXBElement<Value>(_Value_QNAME, Value.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Enumerate }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Enumerate }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "enumerate", substitutionHeadNamespace = "http://www.w3.org/2001/vxml", substitutionHeadName = "aws")
    public JAXBElement<Enumerate> createEnumerate(Enumerate value) {
        return new JAXBElement<Enumerate>(_Enumerate_QNAME, Enumerate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VxmlSpeak }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link VxmlSpeak }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "prompt")
    public JAXBElement<VxmlSpeak> createPrompt(VxmlSpeak value) {
        return new JAXBElement<VxmlSpeak>(_Prompt_QNAME, VxmlSpeak.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BasicEventHandler }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BasicEventHandler }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "error")
    public JAXBElement<BasicEventHandler> createError(BasicEventHandler value) {
        return new JAXBElement<BasicEventHandler>(_Error_QNAME, BasicEventHandler.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BasicEventHandler }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BasicEventHandler }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "help")
    public JAXBElement<BasicEventHandler> createHelp(BasicEventHandler value) {
        return new JAXBElement<BasicEventHandler>(_Help_QNAME, BasicEventHandler.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BasicEventHandler }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BasicEventHandler }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "noinput")
    public JAXBElement<BasicEventHandler> createNoinput(BasicEventHandler value) {
        return new JAXBElement<BasicEventHandler>(_Noinput_QNAME, BasicEventHandler.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BasicEventHandler }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BasicEventHandler }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "nomatch")
    public JAXBElement<BasicEventHandler> createNomatch(BasicEventHandler value) {
        return new JAXBElement<BasicEventHandler>(_Nomatch_QNAME, BasicEventHandler.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ForeachNotInPromptType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ForeachNotInPromptType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "foreach", scope = If.class)
    public JAXBElement<ForeachNotInPromptType> createIfForeach(ForeachNotInPromptType value) {
        return new JAXBElement<ForeachNotInPromptType>(_IfForeach_QNAME, ForeachNotInPromptType.class, If.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ForeachNotInPromptType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ForeachNotInPromptType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "foreach", scope = Block.class)
    public JAXBElement<ForeachNotInPromptType> createBlockForeach(ForeachNotInPromptType value) {
        return new JAXBElement<ForeachNotInPromptType>(_IfForeach_QNAME, ForeachNotInPromptType.class, Block.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ForeachNotInPromptType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ForeachNotInPromptType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "foreach", scope = BasicEventHandler.class)
    public JAXBElement<ForeachNotInPromptType> createBasicEventHandlerForeach(ForeachNotInPromptType value) {
        return new JAXBElement<ForeachNotInPromptType>(_IfForeach_QNAME, ForeachNotInPromptType.class, BasicEventHandler.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MixedGrammar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MixedGrammar }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "grammar", scope = Choice.class)
    public JAXBElement<MixedGrammar> createChoiceGrammar(MixedGrammar value) {
        return new JAXBElement<MixedGrammar>(_Grammar_QNAME, MixedGrammar.class, Choice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ForeachNotInPromptType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ForeachNotInPromptType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "foreach", scope = Filled.class)
    public JAXBElement<ForeachNotInPromptType> createFilledForeach(ForeachNotInPromptType value) {
        return new JAXBElement<ForeachNotInPromptType>(_IfForeach_QNAME, ForeachNotInPromptType.class, Filled.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MixedGrammar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MixedGrammar }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "grammar", scope = Field.class)
    public JAXBElement<MixedGrammar> createFieldGrammar(MixedGrammar value) {
        return new JAXBElement<MixedGrammar>(_Grammar_QNAME, MixedGrammar.class, Field.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MixedGrammar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MixedGrammar }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "grammar", scope = Record.class)
    public JAXBElement<MixedGrammar> createRecordGrammar(MixedGrammar value) {
        return new JAXBElement<MixedGrammar>(_Grammar_QNAME, MixedGrammar.class, Record.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MixedGrammar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MixedGrammar }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "grammar", scope = Transfer.class)
    public JAXBElement<MixedGrammar> createTransferGrammar(MixedGrammar value) {
        return new JAXBElement<MixedGrammar>(_Grammar_QNAME, MixedGrammar.class, Transfer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MixedGrammar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link MixedGrammar }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "grammar", scope = Form.class)
    public JAXBElement<MixedGrammar> createFormGrammar(MixedGrammar value) {
        return new JAXBElement<MixedGrammar>(_Grammar_QNAME, MixedGrammar.class, Form.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ForeachInPromptType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ForeachInPromptType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "foreach", scope = ForeachInPromptType.class)
    public JAXBElement<ForeachInPromptType> createForeachInPromptTypeForeach(ForeachInPromptType value) {
        return new JAXBElement<ForeachInPromptType>(_IfForeach_QNAME, ForeachInPromptType.class, ForeachInPromptType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Token }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Token }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "token", scope = Rule.class)
    public JAXBElement<Token> createRuleToken(Token value) {
        return new JAXBElement<Token>(_RuleToken_QNAME, Token.class, Rule.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ruleref }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Ruleref }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "ruleref", scope = Rule.class)
    public JAXBElement<Ruleref> createRuleRuleref(Ruleref value) {
        return new JAXBElement<Ruleref>(_RuleRuleref_QNAME, Ruleref.class, Rule.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Item }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Item }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "item", scope = Rule.class)
    public JAXBElement<Item> createRuleItem(Item value) {
        return new JAXBElement<Item>(_RuleItem_QNAME, Item.class, Rule.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OneOf }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OneOf }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "one-of", scope = Rule.class)
    public JAXBElement<OneOf> createRuleOneOf(OneOf value) {
        return new JAXBElement<OneOf>(_RuleOneOf_QNAME, OneOf.class, Rule.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "tag", scope = Rule.class)
    public JAXBElement<String> createRuleTag(String value) {
        return new JAXBElement<String>(_RuleTag_QNAME, String.class, Rule.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "example", scope = Rule.class)
    public JAXBElement<String> createRuleExample(String value) {
        return new JAXBElement<String>(_RuleExample_QNAME, String.class, Rule.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Token }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Token }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "token", scope = Item.class)
    public JAXBElement<Token> createItemToken(Token value) {
        return new JAXBElement<Token>(_RuleToken_QNAME, Token.class, Item.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ruleref }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Ruleref }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "ruleref", scope = Item.class)
    public JAXBElement<Ruleref> createItemRuleref(Ruleref value) {
        return new JAXBElement<Ruleref>(_RuleRuleref_QNAME, Ruleref.class, Item.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Item }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Item }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "item", scope = Item.class)
    public JAXBElement<Item> createItemItem(Item value) {
        return new JAXBElement<Item>(_RuleItem_QNAME, Item.class, Item.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OneOf }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link OneOf }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "one-of", scope = Item.class)
    public JAXBElement<OneOf> createItemOneOf(OneOf value) {
        return new JAXBElement<OneOf>(_RuleOneOf_QNAME, OneOf.class, Item.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "tag", scope = Item.class)
    public JAXBElement<String> createItemTag(String value) {
        return new JAXBElement<String>(_RuleTag_QNAME, String.class, Item.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Lexicon }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Lexicon }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "lexicon", scope = OriginalMixedGrammar.class)
    public JAXBElement<Lexicon> createOriginalMixedGrammarLexicon(Lexicon value) {
        return new JAXBElement<Lexicon>(_OriginalMixedGrammarLexicon_QNAME, Lexicon.class, OriginalMixedGrammar.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Meta }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Meta }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "meta", scope = OriginalMixedGrammar.class)
    public JAXBElement<Meta> createOriginalMixedGrammarMeta(Meta value) {
        return new JAXBElement<Meta>(_OriginalMixedGrammarMeta_QNAME, Meta.class, OriginalMixedGrammar.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Metadata }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Metadata }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "metadata", scope = OriginalMixedGrammar.class)
    public JAXBElement<Metadata> createOriginalMixedGrammarMetadata(Metadata value) {
        return new JAXBElement<Metadata>(_OriginalMixedGrammarMetadata_QNAME, Metadata.class, OriginalMixedGrammar.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "tag", scope = OriginalMixedGrammar.class)
    public JAXBElement<String> createOriginalMixedGrammarTag(String value) {
        return new JAXBElement<String>(_RuleTag_QNAME, String.class, OriginalMixedGrammar.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Rule }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Rule }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "rule", scope = OriginalMixedGrammar.class)
    public JAXBElement<Rule> createOriginalMixedGrammarRule(Rule value) {
        return new JAXBElement<Rule>(_OriginalMixedGrammarRule_QNAME, Rule.class, OriginalMixedGrammar.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SsmlMeta }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SsmlMeta }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "meta", scope = VxmlSpeak.class)
    public JAXBElement<SsmlMeta> createVxmlSpeakMeta(SsmlMeta value) {
        return new JAXBElement<SsmlMeta>(_OriginalMixedGrammarMeta_QNAME, SsmlMeta.class, VxmlSpeak.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SsmlMetadata }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SsmlMetadata }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "metadata", scope = VxmlSpeak.class)
    public JAXBElement<SsmlMetadata> createVxmlSpeakMetadata(SsmlMetadata value) {
        return new JAXBElement<SsmlMetadata>(_OriginalMixedGrammarMetadata_QNAME, SsmlMetadata.class, VxmlSpeak.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SsmlLexicon }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SsmlLexicon }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "lexicon", scope = VxmlSpeak.class)
    public JAXBElement<SsmlLexicon> createVxmlSpeakLexicon(SsmlLexicon value) {
        return new JAXBElement<SsmlLexicon>(_OriginalMixedGrammarLexicon_QNAME, SsmlLexicon.class, VxmlSpeak.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ForeachInPromptType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ForeachInPromptType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "foreach", scope = VxmlSpeak.class)
    public JAXBElement<ForeachInPromptType> createVxmlSpeakForeach(ForeachInPromptType value) {
        return new JAXBElement<ForeachInPromptType>(_IfForeach_QNAME, ForeachInPromptType.class, VxmlSpeak.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ForeachNotInPromptType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ForeachNotInPromptType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "foreach", scope = ForeachNotInPromptType.class)
    public JAXBElement<ForeachNotInPromptType> createForeachNotInPromptTypeForeach(ForeachNotInPromptType value) {
        return new JAXBElement<ForeachNotInPromptType>(_IfForeach_QNAME, ForeachNotInPromptType.class, ForeachNotInPromptType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ForeachInPromptType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ForeachInPromptType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "foreach", scope = Enumerate.class)
    public JAXBElement<ForeachInPromptType> createEnumerateForeach(ForeachInPromptType value) {
        return new JAXBElement<ForeachInPromptType>(_IfForeach_QNAME, ForeachInPromptType.class, Enumerate.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SsmlMeta }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SsmlMeta }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "meta", scope = Speak.class)
    public JAXBElement<SsmlMeta> createSpeakMeta(SsmlMeta value) {
        return new JAXBElement<SsmlMeta>(_OriginalMixedGrammarMeta_QNAME, SsmlMeta.class, Speak.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SsmlMetadata }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SsmlMetadata }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "metadata", scope = Speak.class)
    public JAXBElement<SsmlMetadata> createSpeakMetadata(SsmlMetadata value) {
        return new JAXBElement<SsmlMetadata>(_OriginalMixedGrammarMetadata_QNAME, SsmlMetadata.class, Speak.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SsmlLexicon }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SsmlLexicon }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2001/vxml", name = "lexicon", scope = Speak.class)
    public JAXBElement<SsmlLexicon> createSpeakLexicon(SsmlLexicon value) {
        return new JAXBElement<SsmlLexicon>(_OriginalMixedGrammarLexicon_QNAME, SsmlLexicon.class, Speak.class, value);
    }

}
