//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.14 at 08:28:06 AM EDT 
//


package com.nextivr.voicexml21;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for strength.datatype.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="strength.datatype"&amp;gt;
 *   &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *     &amp;lt;enumeration value="none"/&amp;gt;
 *     &amp;lt;enumeration value="x-weak"/&amp;gt;
 *     &amp;lt;enumeration value="weak"/&amp;gt;
 *     &amp;lt;enumeration value="medium"/&amp;gt;
 *     &amp;lt;enumeration value="strong"/&amp;gt;
 *     &amp;lt;enumeration value="x-strong"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "strength.datatype")
@XmlEnum
public enum StrengthDatatype {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("x-weak")
    X_WEAK("x-weak"),
    @XmlEnumValue("weak")
    WEAK("weak"),
    @XmlEnumValue("medium")
    MEDIUM("medium"),
    @XmlEnumValue("strong")
    STRONG("strong"),
    @XmlEnumValue("x-strong")
    X_STRONG("x-strong");
    private final String value;

    StrengthDatatype(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StrengthDatatype fromValue(String v) {
        for (StrengthDatatype c: StrengthDatatype.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
