//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.14 at 08:28:06 AM EDT 
//


package com.nextivr.vxml.voicexml21;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for GrammarScope.datatype.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="GrammarScope.datatype"&amp;gt;
 *   &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&amp;gt;
 *     &amp;lt;enumeration value="document"/&amp;gt;
 *     &amp;lt;enumeration value="dialog"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "GrammarScope.datatype")
@XmlEnum
public enum GrammarScopeDatatype {

    @XmlEnumValue("document")
    DOCUMENT("document"),
    @XmlEnumValue("dialog")
    DIALOG("dialog");
    private final String value;

    GrammarScopeDatatype(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GrammarScopeDatatype fromValue(String v) {
        for (GrammarScopeDatatype c: GrammarScopeDatatype.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
