//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.14 at 08:28:06 AM EDT 
//


package com.nextivr.vxml.voicexml21;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * extends mark type with VoiceXML 'nameexpr'
 * 
 * &lt;p&gt;Java class for mark complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="mark"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{http://www.w3.org/2001/vxml}mark"&amp;gt;
 *       &amp;lt;redefine&amp;gt;
 *         &amp;lt;complexType name="mark"&amp;gt;
 *           &amp;lt;complexContent&amp;gt;
 *             &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *               &amp;lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}token" /&amp;gt;
 *             &amp;lt;/restriction&amp;gt;
 *           &amp;lt;/complexContent&amp;gt;
 *         &amp;lt;/complexType&amp;gt;
 *       &amp;lt;/redefine&amp;gt;
 *       &amp;lt;attribute name="nameexpr" type="{http://www.w3.org/2001/vxml}Script.datatype" /&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mark")
public class Mark
    extends OriginalMark
{

    @XmlAttribute(name = "nameexpr")
    protected String nameexpr;

    /**
     * Gets the value of the nameexpr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameexpr() {
        return nameexpr;
    }

    /**
     * Sets the value of the nameexpr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameexpr(String value) {
        this.nameexpr = value;
    }

}
