//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.14 at 08:28:06 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/2001/vxml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.nextivr.vxml.voicexml21;
