//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.14 at 08:28:06 AM EDT 
//


package com.nextivr.vxml.voicexml21;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * extends say-as type by allowing the value element as a child
 * 
 * &lt;p&gt;Java class for say-as complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="say-as"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;extension base="{http://www.w3.org/2001/vxml}say-as"&amp;gt;
 *       &amp;lt;redefine&amp;gt;
 *         &amp;lt;complexType name="say-as"&amp;gt;
 *           &amp;lt;complexContent&amp;gt;
 *             &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *               &amp;lt;attribute name="interpret-as" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" /&amp;gt;
 *               &amp;lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" /&amp;gt;
 *               &amp;lt;attribute name="detail" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" /&amp;gt;
 *             &amp;lt;/restriction&amp;gt;
 *           &amp;lt;/complexContent&amp;gt;
 *         &amp;lt;/complexType&amp;gt;
 *       &amp;lt;/redefine&amp;gt;
 *       &amp;lt;choice maxOccurs="unbounded" minOccurs="0"&amp;gt;
 *         &amp;lt;element ref="{http://www.w3.org/2001/vxml}value"/&amp;gt;
 *       &amp;lt;/choice&amp;gt;
 *     &amp;lt;/extension&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "say-as")
public class SayAs
    extends OriginalSayAs
{


}
