//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.14 at 08:28:06 AM EDT 
//


package com.nextivr.vxml.voicexml21;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for volume.scale.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="volume.scale"&amp;gt;
 *   &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&amp;gt;
 *     &amp;lt;enumeration value="silent"/&amp;gt;
 *     &amp;lt;enumeration value="x-soft"/&amp;gt;
 *     &amp;lt;enumeration value="soft"/&amp;gt;
 *     &amp;lt;enumeration value="medium"/&amp;gt;
 *     &amp;lt;enumeration value="loud"/&amp;gt;
 *     &amp;lt;enumeration value="x-loud"/&amp;gt;
 *     &amp;lt;enumeration value="default"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "volume.scale")
@XmlEnum
public enum VolumeScale {

    @XmlEnumValue("silent")
    SILENT("silent"),
    @XmlEnumValue("x-soft")
    X_SOFT("x-soft"),
    @XmlEnumValue("soft")
    SOFT("soft"),
    @XmlEnumValue("medium")
    MEDIUM("medium"),
    @XmlEnumValue("loud")
    LOUD("loud"),
    @XmlEnumValue("x-loud")
    X_LOUD("x-loud"),
    @XmlEnumValue("default")
    DEFAULT("default");
    private final String value;

    VolumeScale(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VolumeScale fromValue(String v) {
        for (VolumeScale c: VolumeScale.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
